# Generated by Django 6.1 on 2026-10-07 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, upload_to='sheets/%Y/%m/', verbose_name='foto')),
                ('supplier_name_read', models.CharField(blank=True, max_length=200, verbose_name='proveedor leído')),
                ('document_type', models.CharField(blank=True, max_length=60, verbose_name='tipo de documento')),
                ('folio', models.CharField(blank=True, max_length=60, verbose_name='folio')),
                ('sheet_date', models.DateField(blank=True, null=True, verbose_name='fecha de la hoja')),
                ('subtotal_read', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='subtotal leído')),
                ('total_read', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='total leído')),
                ('model_used', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='tokens de entrada')),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='tokens de salida')),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='costo USD')),
                ('seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='segundos')),
                ('raw_reading', models.JSONField(blank=True, null=True, verbose_name='lectura cruda')),
                ('status', models.CharField(choices=[('read', 'Leída'), ('in_review', 'En revisión'), ('confirmed', 'Confirmada'), ('discarded', 'Descartada')], default='read', max_length=12, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmada en')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sheets', to='catalog.supplier', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'hoja recibida',
                'verbose_name_plural': 'hojas recibidas',
                'db_table': 'received_sheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(verbose_name='renglón')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='cantidad')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='unidad')),
                ('supplier_code', models.CharField(blank=True, max_length=60, verbose_name='clave del proveedor')),
                ('description', models.CharField(max_length=300, verbose_name='descripción')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo unitario')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe')),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='confianza')),
                ('amount_matches', models.BooleanField(verbose_name='cuadra')),
                ('status', models.CharField(choices=[('resolved', 'Resuelto'), ('flagged', 'Separado'), ('confirmed', 'Confirmado'), ('discarded', 'Descartado')], default='resolved', max_length=10, verbose_name='estado')),
                ('reason', models.CharField(blank=True, choices=[('', 'Ninguno'), ('amount_mismatch', 'El importe no coincide'), ('illegible_text', 'Texto ilegible'), ('unrecognized_product', 'Producto no reconocido'), ('cost_variation', 'Variación de costo')], default='', max_length=24, verbose_name='motivo')),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='cantidad recibida')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio público')),
                ('corrected_by_person', models.BooleanField(default=False, verbose_name='corregido por la persona')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product', verbose_name='producto')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='receiving.receivedsheet', verbose_name='hoja')),
            ],
            options={
                'verbose_name': 'renglón provisional',
                'verbose_name_plural': 'renglones provisionales',
                'db_table': 'provisional_lines',
                'ordering': ['sheet', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmedEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField(verbose_name='fecha')),
                ('folio', models.CharField(blank=True, max_length=60, verbose_name='folio')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='confirmada por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='catalog.supplier', verbose_name='proveedor')),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entry', to='receiving.receivedsheet', verbose_name='hoja')),
            ],
            options={
                'verbose_name': 'entrada confirmada',
                'verbose_name_plural': 'entradas confirmadas',
                'db_table': 'confirmed_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo unitario')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio público')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='receiving.confirmedentry', verbose_name='entrada')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product', verbose_name='producto')),
                ('source_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_line', to='receiving.provisionalline', verbose_name='renglón de origen')),
            ],
            options={
                'verbose_name': 'renglón de entrada',
                'verbose_name_plural': 'renglones de entrada',
                'db_table': 'entry_lines',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='entry_lines_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='entry_lines_cost_not_negative'), models.CheckConstraint(condition=models.Q(('retail_price__isnull', True), ('retail_price__gte', 0), _connector='OR'), name='entry_lines_price_not_negative')],
            },
        ),
        migrations.AddConstraint(
            model_name='receivedsheet',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['read', 'in_review', 'confirmed', 'discarded'])), name='received_sheets_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='receivedsheet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', False), ('status', 'confirmed')), models.Q(models.Q(('status', 'confirmed'), _negated=True), ('confirmed_at__isnull', True)), _connector='OR'), name='received_sheets_confirmed_has_date'),
        ),
        migrations.AddConstraint(
            model_name='receivedsheet',
            constraint=models.CheckConstraint(condition=models.Q(('cost_usd__isnull', True), ('cost_usd__gte', 0), _connector='OR'), name='received_sheets_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.UniqueConstraint(fields=('sheet', 'position'), name='provisional_lines_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['resolved', 'flagged', 'confirmed', 'discarded'])), name='provisional_lines_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['', 'amount_mismatch', 'illegible_text', 'unrecognized_product', 'cost_variation'])), name='provisional_lines_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'flagged'), _negated=True), ('reason__in', ['amount_mismatch', 'illegible_text', 'unrecognized_product']), _connector='OR'), name='provisional_lines_flagged_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'resolved'), _negated=True), ('reason__in', ['', 'cost_variation']), _connector='OR'), name='provisional_lines_resolved_reason'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='provisional_lines_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('description__regex', '\\S')), name='provisional_lines_description_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__isnull', True), ('received_quantity__gte', 0), _connector='OR'), name='provisional_lines_received_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('retail_price__isnull', True), ('retail_price__gte', 0), _connector='OR'), name='provisional_lines_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='confirmedentry',
            constraint=models.CheckConstraint(condition=models.Q(('total__isnull', True), ('total__gte', 0), _connector='OR'), name='confirmed_entries_total_not_negative'),
        ),
    ]
