# Generated by Django 6.1 on 2026-10-08 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('upload_order', models.PositiveSmallIntegerField(verbose_name='orden')),
                ('printed_page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='página impresa')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='archivo original')),
                ('file_sha256', models.CharField(db_index=True, max_length=64, verbose_name='huella')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='tomada en')),
                ('width', models.PositiveIntegerField(verbose_name='ancho')),
                ('height', models.PositiveIntegerField(verbose_name='alto')),
                ('file_size', models.PositiveIntegerField(verbose_name='tamaño')),
                ('thumbnail', models.BinaryField(verbose_name='miniatura')),
                ('device', models.CharField(blank=True, max_length=200, verbose_name='dispositivo')),
                ('read_status', models.CharField(choices=[('pending', 'Pendiente'), ('read', 'Leída'), ('failed', 'Falló')], default='pending', max_length=8, verbose_name='lectura')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='subida por')),
            ],
            options={
                'verbose_name': 'página',
                'verbose_name_plural': 'páginas',
                'db_table': 'document_pages',
                'ordering': ['document', 'upload_order'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('status', models.CharField(choices=[('reading', 'Leyendo'), ('in_review', 'En revisión'), ('confirmed', 'Confirmado'), ('discarded', 'Descartado')], default='reading', max_length=10, verbose_name='estado')),
                ('supplier_name_read', models.CharField(blank=True, max_length=200, verbose_name='proveedor leído')),
                ('supplier_rfc_read', models.CharField(blank=True, max_length=13, verbose_name='RFC leído')),
                ('document_type_read', models.CharField(blank=True, max_length=60, verbose_name='tipo leído')),
                ('folio_read', models.CharField(blank=True, max_length=60, verbose_name='folio leído')),
                ('document_date_read', models.DateField(blank=True, null=True, verbose_name='fecha leída')),
                ('subtotal_read', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='subtotal leído')),
                ('tax_read', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='IVA leído')),
                ('total_read', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='total leído')),
                ('printed_page_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='páginas impresas')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='avisos')),
                ('thresholds', models.JSONField(blank=True, default=dict, verbose_name='umbrales')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalog.supplier', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'documento recibido',
                'verbose_name_plural': 'documentos recibidos',
                'db_table': 'received_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('position', models.PositiveSmallIntegerField(verbose_name='renglón')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='cantidad')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='unidad')),
                ('supplier_code', models.CharField(blank=True, max_length=60, verbose_name='clave del proveedor')),
                ('description', models.CharField(max_length=300, verbose_name='descripción')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo unitario')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe')),
                ('handwritten_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio escrito a mano')),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='confianza')),
                ('amount_matches', models.BooleanField(blank=True, null=True, verbose_name='cuadra')),
                ('status', models.CharField(choices=[('resolved', 'Resuelto'), ('flagged', 'Separado'), ('confirmed', 'Confirmado'), ('discarded', 'No llegó')], default='resolved', max_length=10, verbose_name='estado')),
                ('reason', models.CharField(blank=True, choices=[('', 'Ninguno'), ('missing_value', 'Falta un dato'), ('amount_mismatch', 'Cantidad por costo no da el importe'), ('illegible_text', 'Lectura dudosa'), ('code_mismatch', 'La clave no corresponde a la descripción'), ('unrecognized_product', 'Producto no reconocido'), ('cost_variation', 'El costo cambió')], default='', max_length=24, verbose_name='motivo')),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='cantidad recibida')),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='margen %')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio público')),
                ('corrected_by_person', models.BooleanField(default=False, verbose_name='corregido por la persona')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='receiving.documentpage', verbose_name='página')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product', verbose_name='producto')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='receiving.receiveddocument', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'renglón provisional',
                'verbose_name_plural': 'renglones provisionales',
                'db_table': 'provisional_lines',
                'ordering': ['document', 'position'],
            },
        ),
        migrations.AddField(
            model_name='documentpage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='receiving.receiveddocument', verbose_name='documento'),
        ),
        migrations.CreateModel(
            name='ConfirmedEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('folio', models.CharField(blank=True, max_length=60, verbose_name='folio')),
                ('entry_date', models.DateField(verbose_name='fecha')),
                ('printed_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='total impreso')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='confirmada en')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='confirmada por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='catalog.supplier', verbose_name='proveedor')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entry', to='receiving.receiveddocument', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'entrada confirmada',
                'verbose_name_plural': 'entradas confirmadas',
                'db_table': 'confirmed_entries',
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='PageReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('ok', 'Correcta'), ('auth', 'Llave inválida'), ('no_credit', 'Sin crédito'), ('rate_limit', 'Demasiadas peticiones'), ('provider_down', 'Servicio caído'), ('timeout', 'Tiempo agotado'), ('truncated', 'Respuesta cortada'), ('invalid_json', 'Respuesta ilegible'), ('schema', 'Respuesta fuera del formato'), ('not_a_document', 'No es una hoja de proveedor')], max_length=14, verbose_name='resultado')),
                ('error_detail', models.CharField(blank=True, max_length=500, verbose_name='detalle')),
                ('model', models.CharField(max_length=100, verbose_name='modelo')),
                ('provider', models.CharField(blank=True, max_length=60, verbose_name='proveedor del modelo')),
                ('prompt_version', models.CharField(max_length=20, verbose_name='versión del prompt')),
                ('image_side', models.PositiveSmallIntegerField(verbose_name='lado enviado (px)')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='tokens de entrada')),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='tokens de salida')),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='costo USD')),
                ('seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='segundos')),
                ('from_cache', models.BooleanField(default=False, verbose_name='lectura guardada')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='receiving.documentpage', verbose_name='página')),
            ],
            options={
                'verbose_name': 'lectura',
                'verbose_name_plural': 'lecturas',
                'db_table': 'page_readings',
                'ordering': ['page', 'created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome__in', ['ok', 'auth', 'no_credit', 'rate_limit', 'provider_down', 'timeout', 'truncated', 'invalid_json', 'schema', 'not_a_document'])), name='page_readings_outcome_valid'), models.CheckConstraint(condition=models.Q(('cost_usd__isnull', True), ('cost_usd__gte', 0), _connector='OR'), name='page_readings_cost_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='EntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo unitario')),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='margen %')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio público')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='receiving.confirmedentry', verbose_name='entrada')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_lines', to='catalog.product', verbose_name='producto')),
                ('source_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entry_line', to='receiving.provisionalline', verbose_name='renglón de origen')),
            ],
            options={
                'verbose_name': 'renglón de entrada',
                'verbose_name_plural': 'renglones de entrada',
                'db_table': 'entry_lines',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='entry_lines_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='entry_lines_cost_not_negative'), models.CheckConstraint(condition=models.Q(('margin_percent__isnull', True), ('margin_percent__gte', 0), _connector='OR'), name='entry_lines_margin_not_negative'), models.CheckConstraint(condition=models.Q(('retail_price__isnull', True), ('retail_price__gte', 0), _connector='OR'), name='entry_lines_price_not_negative')],
            },
        ),
        migrations.AddConstraint(
            model_name='receiveddocument',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['reading', 'in_review', 'confirmed', 'discarded'])), name='received_documents_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.UniqueConstraint(fields=('document', 'position'), name='provisional_lines_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['resolved', 'flagged', 'confirmed', 'discarded'])), name='provisional_lines_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['', 'missing_value', 'amount_mismatch', 'illegible_text', 'code_mismatch', 'unrecognized_product', 'cost_variation'])), name='provisional_lines_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'flagged'), _negated=True), ('reason__in', ['missing_value', 'amount_mismatch', 'illegible_text', 'code_mismatch', 'unrecognized_product']), _connector='OR'), name='provisional_lines_flagged_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'resolved'), _negated=True), ('reason__in', ['', 'cost_variation']), _connector='OR'), name='provisional_lines_resolved_reason'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_matches__isnull', True), ('quantity__isnull', True)), models.Q(('amount_matches__isnull', False), ('quantity__isnull', False)), _connector='OR'), name='provisional_lines_matches_needs_quantity'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'discarded'), _negated=True), ('received_quantity', 0), _connector='OR'), name='provisional_lines_discarded_received_zero'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='provisional_lines_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('description__regex', '\\S')), name='provisional_lines_description_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__isnull', True), ('received_quantity__gte', 0), _connector='OR'), name='provisional_lines_received_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('margin_percent__isnull', True), ('margin_percent__gte', 0), _connector='OR'), name='provisional_lines_margin_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('retail_price__isnull', True), ('retail_price__gte', 0), _connector='OR'), name='provisional_lines_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('handwritten_price__isnull', True), ('handwritten_price__gte', 0), _connector='OR'), name='provisional_lines_handwritten_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.UniqueConstraint(fields=('document', 'upload_order'), name='document_pages_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.CheckConstraint(condition=models.Q(('read_status__in', ['pending', 'read', 'failed'])), name='document_pages_read_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.CheckConstraint(condition=models.Q(('file_sha256__regex', '^[0-9a-f]{64}$')), name='document_pages_sha256_format'),
        ),
        migrations.AddConstraint(
            model_name='confirmedentry',
            constraint=models.UniqueConstraint(condition=models.Q(('folio', ''), _negated=True), fields=('supplier', 'folio'), name='confirmed_entries_folio_unique'),
        ),
        migrations.AddConstraint(
            model_name='confirmedentry',
            constraint=models.CheckConstraint(condition=models.Q(('printed_total__isnull', True), ('printed_total__gte', 0), _connector='OR'), name='confirmed_entries_total_not_negative'),
        ),
    ]
