# Generated by Django 6.1 on 2026-10-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalline',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='descuento %'),
        ),
        migrations.AddConstraint(
            model_name='provisionalline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__isnull', True), models.Q(('discount_percent__gte', 0), ('discount_percent__lt', 100)), _connector='OR'), name='provisional_lines_discount_range'),
        ),
    ]
