# Generated by Django 6.1 on 2026-10-08 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=60, verbose_name='tabla')),
                ('row_id', models.UUIDField(verbose_name='registro')),
                ('action', models.CharField(choices=[('create', 'Alta'), ('update', 'Cambio')], max_length=6, verbose_name='acción')),
                ('changes', models.JSONField(verbose_name='cambios')),
                ('source', models.CharField(choices=[('reader', 'Lectura'), ('review', 'Revisión'), ('confirm', 'Confirmación'), ('admin', 'Administración'), ('app', 'Aplicación')], max_length=10, verbose_name='origen')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='hecho por')),
            ],
            options={
                'verbose_name': 'cambio',
                'verbose_name_plural': 'historial de cambios',
                'db_table': 'change_log',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['table_name', 'row_id', 'changed_at'], name='change_log_row_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['create', 'update'])), name='change_log_action_valid'), models.CheckConstraint(condition=models.Q(('source__in', ['reader', 'review', 'confirm', 'admin', 'app'])), name='change_log_source_valid')],
            },
        ),
    ]
