# Generated by Django 6.1 on 2026-10-08 16:49

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='unidad')),
                ('last_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='último costo')),
                ('cost_source', models.CharField(choices=[('supplier', 'De proveedor'), ('estimated', 'Estimado'), ('unknown', 'Desconocido')], default='unknown', max_length=12, verbose_name='origen del costo')),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='margen %')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio público')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'products',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='products_name_not_blank'), models.CheckConstraint(condition=models.Q(('cost_source__in', ['supplier', 'estimated', 'unknown'])), name='products_cost_source_valid'), models.CheckConstraint(condition=models.Q(('last_cost__isnull', True), ('last_cost__gte', 0), _connector='OR'), name='products_cost_not_negative'), models.CheckConstraint(condition=models.Q(('margin_percent__isnull', True), ('margin_percent__gte', 0), _connector='OR'), name='products_margin_not_negative'), models.CheckConstraint(condition=models.Q(('retail_price__isnull', True), ('retail_price__gte', 0), _connector='OR'), name='products_price_not_negative'), models.CheckConstraint(condition=models.Q(models.Q(('cost_source', 'unknown'), ('last_cost__isnull', True)), models.Q(('last_cost__isnull', False), models.Q(('cost_source', 'unknown'), _negated=True)), _connector='OR'), name='products_cost_and_source_consistent')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'suppliers',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='suppliers_name_unique'), models.UniqueConstraint(condition=models.Q(('rfc', ''), _negated=True), fields=('rfc',), name='suppliers_rfc_unique'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='suppliers_name_not_blank'), models.CheckConstraint(condition=models.Q(('rfc', ''), ('rfc__regex', '^[A-ZÑ&]{3,4}[0-9]{6}[A-Z0-9]{3}$'), _connector='OR'), name='suppliers_rfc_format')],
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('alias', models.CharField(max_length=300, verbose_name='nombre alterno')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='catalog.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'nombre alterno',
                'verbose_name_plural': 'nombres alternos',
                'db_table': 'product_aliases',
                'constraints': [models.UniqueConstraint(models.F('product'), django.db.models.functions.text.Lower('alias'), name='product_aliases_unique'), models.CheckConstraint(condition=models.Q(('alias__regex', '\\S')), name='product_aliases_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplierCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('code', models.CharField(max_length=60, verbose_name='clave')),
                ('supplier_description', models.CharField(blank=True, max_length=300, verbose_name='descripción del proveedor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_codes', to='catalog.product', verbose_name='producto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_codes', to='catalog.supplier', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'clave de proveedor',
                'verbose_name_plural': 'claves de proveedor',
                'db_table': 'product_supplier_codes',
                'constraints': [models.UniqueConstraint(fields=('supplier', 'code'), name='product_supplier_codes_unique'), models.CheckConstraint(condition=models.Q(('code__regex', '\\S')), name='product_supplier_codes_code_not_blank')],
            },
        ),
    ]
